---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  template:
    spec:
      containers:
      - name: webserver-simple
        env:
        - name: UI_THEME
          value: "Dark"
        - name: PAGE_LIMIT
          value: "25"
        - name: SORTING
          value: "ascending"    
        - name: N_BUCKETS
          value: "42"
        - name: ENV
          value: "dev"
        - name: GPU_ENABLED
          value: "1"
        - name: ENV_TYPE
          value: "non-prod"
        - name: PAYPAL_URL
          value: "dev.paypal.com"
        - name: DB_USER
          value: "non-prod-user"
        - name: DB_PASSWORD
          value: "non-prod-password"
        - name: "EXTERNAL_SYSTEM_HOST"
          value: "dev.ext-system.com"